version: "3.7"

services:
  tfs-mnist:
    image: tensorflow/serving
    ports: 
      - 8501:8501
    working_dir: /models/mnist
    environment: 
      MODEL_NAME: mnist
    volumes:
      - /home/boris/models/mnist:/models/mnist
  tfs-flask:
    restart: always
    image: boangri/tfs-flask
    ports:
      - 5000:5000
    working_dir: /usr/src/app
    environment:
      PORT: 5000
    volumes:
      - ./:/usr/src/app
  
